export const stateMap: Record<string, [string, string]> = {
    'al': ['阿尔巴尼亚', 'Albania'],
    'ar': ['阿根廷', 'Argentina'],
    'at': ['奥地利', 'Austria'],
    'au': ['澳大利亚', 'Australia'],
    'be': ['比利时', 'Belgium'],
    'br': ['巴西', 'Brazil'],
    'ca': ['加拿大', 'Canada'],
    'ch': ['瑞士', 'Switzerland'],
    'cm': ['喀麦隆', 'Cameroon'],
    'cr': ['哥斯达黎加', 'Costa Rica'],
    'cz': ['捷克', 'Czech Republic'],
    'de': ['德国', 'Germary'],
    'dk': ['丹麦', 'Denmark'],
    'ec': ['厄瓜多尔', 'Ecuador'],
    'es': ['西班牙', 'Spain'],
    'fr': ['法国', 'France'],
    'gb-eng': ['英格兰', 'England '],
    'gb-sct': ['苏格兰', 'Scotland'],
    'gb-wls': ['威尔士', 'Wales'],
    'ge': ['格鲁吉亚', 'Georgia'],
    'gh': ['加纳', 'Ghana'],
    'hr': ['克罗地亚', 'Croatia'],
    'hu': ['匈牙利', 'Hungary'],
    'ir': ['伊朗', 'Iran'],
    'it': ['意大利', 'Italy'],
    'jp': ['日本', 'Japan'],
    'kr': ['韩国', 'South Korea'],
    'ma': ['摩洛哥', 'Morocco'],
    'mx': ['墨西哥', 'Mexico'],
    'nl': ['荷兰', 'Netherlands'],
    'pl': ['波兰', 'Poland'],
    'pt': ['葡萄牙', 'Portugal'],
    'qa': ['卡塔尔', 'Qatar'],
    'ro': ['罗马尼亚', 'Romania'],
    'rs': ['塞尔维亚', 'Serbia'],
    'sa': ['沙特', 'Saudi Arabia'],
    'si': ['斯洛文尼亚', 'Slovenia'],
    'sk': ['斯洛伐克', 'Slovakia'],
    'sn': ['塞内加尔', 'Senegal'],
    'tn': ['突尼斯', 'Tunisia'],
    'tr': ['土耳其', 'Turkey'],
    'ua': ['乌克兰', 'Ukraine'],
    'us': ['美国', 'USA'],
    'uy': ['乌拉圭', 'Uruguay'],
    '': ['待定', 'TBD'],
    'tbd': ['待定', 'TBD'],
}